name: Deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci --ignore-scripts
        
      - name: Setup SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/deploy_key
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          
      - name: Deploy to VM
        env:
          SSH_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          SSH_HOST: ${{ secrets.AZURE_VM_IP }}
        run: |
          # Create tar preserving paths
          find . -type f -not -path "./node_modules/*" -not -path "./.git/*" -print0 | tar -czf deploy.tar.gz --null -T -
          
          # Copy the tar file to the server
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no deploy.tar.gz $SSH_USERNAME@$SSH_HOST:~/deploy.tar.gz
          
          # Execute deployment commands
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
            set -e
            
            # Stop existing application
            pm2 delete all || true
            sudo pkill node || true
            
            # Clean up and prepare directories
            rm -rf ~/temp_deploy
            mkdir -p ~/temp_deploy
            cd ~/temp_deploy
            
            # Extract new files preserving paths
            tar -xzf ~/deploy.tar.gz
            rm ~/deploy.tar.gz
            
            # Set up environment
            cat > .env << 'EOL'
            CENTRAL_SERVER='${{ secrets.CENTRAL_SERVER }}'
            DO_ENDPOINT='${{ secrets.DO_ENDPOINT }}'
            DO_SPACE_ENDPOINT='${{ secrets.DO_SPACE_ENDPOINT }}'
            DO_SPACE_ID='${{ secrets.DO_SPACE_ID }}'
            DO_SPACE_KEY='${{ secrets.DO_SPACE_KEY }}'
            DO_SPACE_NAME='${{ secrets.DO_SPACE_NAME }}'
            MONGO_URI='${{ secrets.MONGO_URI }}'
            PORT='${{ secrets.PORT }}'
            EOL
            
            # Install dependencies
            npm ci --production
            
            # Backup and replace application directory
            if [ -d ~/myapp ]; then
              rm -rf ~/myapp_backup
              mv ~/myapp ~/myapp_backup
            fi
            mv ~/temp_deploy ~/myapp
            
            # Start application with PM2
            cd ~/myapp
            NODE_ENV=production pm2 start app/app.js --name app
            pm2 save
            
            # Show status
            echo 'PM2 process list:'
            pm2 list
            "

  verify:
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/deploy_key
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

      - name: Wait and Verify Deployment
        env:
          SSH_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          SSH_HOST: ${{ secrets.AZURE_VM_IP }}
        run: |
          echo "Waiting for server to start..."
          sleep 15
          
          echo "Verifying deployment via SSH..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
            cd ~/myapp
            
            echo 'Current directory structure:'
            ls -R
            
            echo 'Attempting to start app...'
            pm2 delete all || true
            pm2 flush
            
            if [ -f app/app.js ]; then
              echo 'Found app.js, starting...'
              NODE_ENV=production pm2 start app/app.js --name app
              pm2 save
              pm2 list
            else
              echo 'app.js not found in expected location'
              exit 1
            fi"