name: Deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci --ignore-scripts
        
      - name: Setup SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/deploy_key
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          
      - name: Deploy to VM
        env:
          SSH_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          SSH_HOST: ${{ secrets.AZURE_VM_IP }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
            # Stop all running processes first
            pm2 kill || true
            sudo pkill node || true
            
            # Clean up PM2
            sudo rm -rf ~/.pm2
            sudo rm -rf /usr/lib/node_modules/pm2
            sudo npm cache clean -f

            # Install Node.js fresh
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&
            sudo apt-get install -y nodejs &&

            # Install PM2
            sudo npm install -g pm2 &&
            cd ~ &&
            pm2 startup ubuntu &&
            sudo env PATH=$PATH:/usr/bin pm2 startup ubuntu -u azureuser --hp /home/azureuser &&

            # Prepare deployment directory
            rm -rf ~/temp_deploy &&
            mkdir -p ~/temp_deploy &&
            cd ~/temp_deploy &&

            # Clone the repository
            git clone 'https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git' . &&

            # Create .env file with secrets
            cat > .env << 'EOL'
            CENTRAL_SERVER="${{ secrets.CENTRAL_SERVER }}"
            DO_ENDPOINT="${{ secrets.DO_ENDPOINT }}"
            DO_SPACE_ENDPOINT="${{ secrets.DO_SPACE_ENDPOINT }}"
            DO_SPACE_ID="${{ secrets.DO_SPACE_ID }}"
            DO_SPACE_KEY="${{ secrets.DO_SPACE_KEY }}"
            DO_SPACE_NAME="${{ secrets.DO_SPACE_NAME }}"
            MONGO_URI="${{ secrets.MONGO_URI }}"
            PORT="${{ secrets.PORT }}"
            EOL

            # Install dependencies
            npm ci --production &&

            # Move the new version into place
            rm -rf ~/myapp &&
            mv ~/temp_deploy ~/myapp &&

            # Start the application
            cd ~/myapp &&
            sleep 10 &&
            NODE_ENV=production pm2 start app/app.js --name app --time &&
            pm2 save &&
            
            # Wait for startup and verify status
            sleep 10 &&
            pm2 status &&
            pm2 logs --lines 20"